name: Build Rust Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          override-file: Cargo.toml

      - name: Build
        run: cargo build --release

      - name: Archive binary
        run: tar -czvf ripley.tar.gz -C target/release ripley

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: | 
            ripley.tar.gz
  
      - name: Publish to Homebrew
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git clone https://github.com/drusellers/homebrew-tap.git
          cd homebrew-tap
          echo "class Ripley < Formula
            desc \"Ripley a database tool\"
            homepage \"https://github.com/drusellers/ripley\"
            url \"https://github.com/drusellers/ripley/releases/download/${{ github.ref }}/ripley.tar.gz\"
            sha256 \"$(shasum -a 256 ../my-crate.tar.gz | awk '{ print $1 }')\"
            version \"${{ github.ref }}\"
  
            def install
              bin.install \"ripley\"
            end
          end" > ripley.rb
          git add ripley.rb
          git commit -m "Update formula for version ${{ github.ref }}"
          git push origin main